spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tarunmadan15@gmail.com
    password: noodpdicyztgngid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

